dataset_path: ./data/dataset.pkl
lookup_table_path: ./data/lookup_table.pkl

# 数据库的总计条目数
corpus_size: 20314045

max_token_len: 512
use_db_cache: false
train_test_split_ratio: 0.8
seed: 1234

# 模型超参数
epoch: 50
batch_size: 10
bert_hidden_size: 84
lr: 0.001
K: 5
vocab_size: 10_000_000
alpha: 0.3
L2_penalty: 1e-5
